#!/bin/sh

# Where the installation scripts live
NUPK_REPOSITORY="/var/db/nupk/repository"
# Where the manifest files live
NUPK_INSTALLED="/var/db/nupk/installed"
# Where the (g)zipped packages live
NUPK_BINARIES="/var/cache/nupk"
# Where packages are built
NUPK_WORKDIR="/var/tmp/nupk"

error_message() {
	printf "\033[31;1m@\033[0m \033[1m$1\033[0m\n"
}

ok_message() {
	printf "\033[32;1m@\033[0m \033[1m$1\033[0m\n"
}

warning_message() {
	printf "\033[33;1m@\033[0m \033[1m$1\033[0m\n"
}

ask_for_cleanup() {
	printf "\033[1mYour response: [Y/n] \033[0m"
	read -r
	if [ $REPLY == 'Y' ] || [ $REPLY == 'y' ]
	then
		rm -rf $1
		ok_message "Removed $1"
	else
		warning_message "$1 untouched"
	fi
}

# Run a build script
build() {
	# $1 is in the form PACKAGE_CLASS/PACKAGE_NAME
	PACKAGE_CLASS="${1%/*}"
	PACKAGE_NAME="${1#*/}"
	SCRIPT_NAME="build-$PACKAGE_NAME.sh"

	# Does a script actually exist?
	if [ ! -f "$NUPK_REPOSITORY/$1/$SCRIPT_NAME" ]
	then
		error_message "A build script for this package could not be found!"
		exit 1
	else
		ok_message "Found a build script for $1"
	fi

	# Very stupid hack until we wrap the scripts content into a function
	VERSION=$(grep '^VERSION' "$NUPK_REPOSITORY/$1/$SCRIPT_NAME" | awk -F '=' '{print $2}')

	# Is the VERSION variable around?
	if [ -z $VERSION ]
	then
		error_message "The build script for $1 does not contain a VERSION variable!"
		exit 1
	else
		ok_message "Found version: $VERSION"
	fi

	# Where the build will take place
	BUILDIR="$NUPK_WORKDIR/$PACKAGE_CLASS-$PACKAGE_NAME"

	# Stop if the remnants of a previous build attempt are found
	if [ -d $BUILDIR ]
	then
		warning_message "Directory $BUILDIR already exists! Remove it now?"
		ask_for_cleanup $BUILDIR
		# If the directory is still there, i.e. the answer was 'no',
		# respect said choice
		[ ! -d $BUILDIR ] || exit
	fi

	# Copy the entire directory
	ok_message "Copying build script and related material..."
	cp -r "$NUPK_REPOSITORY/$1" $BUILDIR
	cd $BUILDIR

	# Build the package
	ok_message "Building directory prepared. Building $1"
	./$SCRIPT_NAME

	# Bail out on failure
	if [ $? != 0 ]
	then
		error_message "Something has gone terribly wrong!"

		# Cleanup, if desired
		warning_message "Remove leftovers in $BUILDIR?"
		ask_for_cleanup $BUILDIR

		error_message "Building $1 failed!"
		exit 1
	else
		# Move the archive to $NUPK_BINARIES
		mv "$PACKAGE_CLASS-$PACKAGE_NAME@$VERSION.tar.gz" $NUPK_BINARIES
		ok_message "$1 built and saved in $NUPK_BINARIES"

		# Cleanup, if desired
		warning_message "Remove leftovers in $BUILDIR?"
		ask_for_cleanup $BUILDIR
	fi
}

# TODO
#install() {
#}

# TODO
#validate() {
#}

# TODO
#update() {
#}

### THE ACTUAL SCRIPT STARTS HERE ###

while getopts "b:" op
do
	# Check if the main directories exist
	# TODO: also check if their permissions have been set properly
	for i in NUPK_REPOSITORY NUPK_INSTALLED NUPK_BINARIES NUPK_WORKDIR
	do
		D=$(eval 'printf ${'"$i"'}')
		if [ ! -e $D ]
		then
			error_message "Directory $i, set as $D, does not exist!"
			exit 1
		fi
	done

	# Check if the package actually exist
	if [ ! -d "$NUPK_REPOSITORY/$OPTARG" ]
	then
		error_message "Package $OPTARG does not exist!"
		exit 1
	fi

	# Prevent root from running a build script
	if [ $(id -u) == 0 ] && [ $op = 'b' ]
	then
		error_message "Only non-root users can build packages"
		exit 1
	fi

	case $op in
	b)
		build $OPTARG
		;;
	esac
done
